Repository jenkinsci/csp-plugin, pull requests merged in 2024-11, with the labels that each got.

#18 Add header at filter layer
  pom.xml
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyDecorator.java
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyFilter.java
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyRootAction.java
  src/main/java/io/jenkins/plugins/csp/Context.java
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyDecorator/httpHeaders.jelly
Labels: bug

#16 Modernise UI components
  pom.xml
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyManagementLink.java
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyManagementLink/index.jelly
Labels: enhancement

#19 Skip setting CSP header on resource root URL request
  README.adoc
  pom.xml
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyFilter.java
  src/test/java/io/jenkins/plugins/csp/ContentSecurityPolicyFilterTest.java
Labels: bug

#20 Fixups to #18
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyFilter.java
Labels: skip-changelog

#22 Copyedit documentation and user-visible strings
  README.adoc
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyConfiguration.java
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyManagementLink.java
  src/main/java/io/jenkins/plugins/csp/ContentSecurityPolicyReceiver.java
  src/main/resources/index.jelly
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyConfiguration/help-reportOnly.html
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyConfiguration/help-rule.jelly
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyManagementLink/index.jelly
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyManagementLink/index.properties
Labels: documentation

#25 Fixup to #16
  src/main/resources/io/jenkins/plugins/csp/ContentSecurityPolicyManagementLink/index.jelly
Labels: skip-changelog
